Update glossary term Admin termination
fecgov/fec-eregs pull request #583
Opened 2021-03-26 14:48 UTC by kathycarothers

Added "administrative termination" to the glossary

Please make sure the end result looks like this:

**Administrative termination** - Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S.C. 30103(d)(2) and 11 CFR 102.4. Administrative termination does not relieve a committee of any legal responsibility for the payment of any outstanding debt or obligations.

And the links for the statute and regs works too. Thank you.

2021-03-26 15:06 UTC, rfultz requested changes
Woo hoo! Thanks, Kathy! Just one tiny just-in-case change?

2021-03-26 15:06 UTC, rfultz commented on fec_eregs/static/fec_eregs/js/data/terms.json
> +    "definition": "Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S
Nice work! For the first link, can we close the space in `href=\" https://www`? I'm not sure if it'll break anything to leave it, but better safe than sorry.

2021-03-26 15:54 UTC, rfultz commented on fec_eregs/static/fec_eregs/js/data/terms.json
> +    "definition": "Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S
Woo hoo! Thanks, @kathycarothers !

2021-03-26 15:55 UTC, rfultz approved these changes

2021-03-26 16:02 UTC, dorothyyeager approved these changes
Looks great. Nice catch @rfultz and great job on this PR @kathycarothers, I know the glossary PRs are not easy.

2021-03-26 16:05 UTC, dorothyyeager requested changes
Looks great and nice catch @rfultz 

One small typo to fix - on line 11, need to add an "i" after the "n" in admin**i**strative.

Thank you @kathycarothers for tackling this!

2021-03-26 16:13 UTC, kathycarothers commented
I have updated line 11

2021-04-02 14:31 UTC, dorothyyeager approved these changes
This looks great. Thanks @kathycarothers

2021-04-02 14:32 UTC, merged