Add additional foreign national terms to glossary
fecgov/fec-eregs pull request #662
Opened 2022-01-27 20:40 UTC by djgarr

## Summary (required)

Add additional foreign national terms to the glossary https://docs.google.com/spreadsheets/d/1iSHhncHt8JCzYrh_UEHmyhoy3sKEpAnNNspCYdS188g/edit#gid=0 (see highlighted)

- Resolves (https://github.com/fecgov/fec-cms/issues/5042)

2022-01-27 20:49 UTC, patphongs requested changes
One minor change

2022-01-27 20:49 UTC, patphongs commented on fec_eregs/static/fec_eregs/js/data/terms.json
> +    "definition": "An individual lawfully admitted for permanent residence is someone who has been granted authorization to live and work in the United States on a permanent basis. As proof of that s
@djgarr When there are quotations as part of the text, it needs to be escaped with a backwarrds slash. Like this `...called a \"Green Card.\""`. After that change, it'll work, thanks!

2022-01-27 21:56 UTC, dorothyyeager approved these changes
Approved from content team perspective. Thanks for taking this on David, nice job!

2022-01-28 14:24 UTC, patphongs approved these changes
All good, thanks again @djgarr !

2022-01-28 14:24 UTC, merged