Update terms.json add compensation #6120
fecgov/fec-eregs pull request #834
Opened 2024-02-15 20:12 UTC by kathycarothers

I have added the term compensation to the list

## Summary (required)

- #6120
- 6124

### Required reviewers

If Pat, John and/or Dorothy could review 

## Impacted areas of the application

General components of the application that this PR will affect:

-  

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- 

## System architecture updates (if applicable)

(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a description of those changes here and create a new ticket to update the system diagram)

2024-02-15 20:41 UTC, patphongs reviewed
Looks good, thanks @kathycarothers !

2024-02-15 20:42 UTC, patphongs approved these changes

2024-02-22 15:38 UTC, dorothyyeager requested changes
Content change - need to add in "Part" before 116.

2024-02-22 20:22 UTC, dorothyyeager approved these changes

2024-02-22 20:22 UTC, merged